# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(default='', max_length=80)),
                ('name', models.CharField(default='Jane', max_length=80)),
                ('middle_name', models.CharField(default='', max_length=80)),
                ('last_name', models.CharField(default='Doe', max_length=80)),
                ('summary', models.TextField(default='The expert.')),
                ('curriculum_vitae', models.TextField(default='')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/avatars/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
