# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('AS', 'Associate')], default='AS', max_length=2),
        ),
    ]
