# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_member_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='curriculum_vitae',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='middle_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='title',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
