# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='address',
        ),
        migrations.RemoveField(
            model_name='article',
            name='city',
        ),
        migrations.RemoveField(
            model_name='article',
            name='country',
        ),
        migrations.RemoveField(
            model_name='article',
            name='name',
        ),
        migrations.RemoveField(
            model_name='article',
            name='zip',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='card_avatar',
            field=models.ImageField(null=True, upload_to='images/avatars/'),
        ),
        migrations.AddField(
            model_name='article',
            name='card_lg_image',
            field=models.ImageField(null=True, upload_to='images/cards/'),
        ),
        migrations.AddField(
            model_name='article',
            name='card_mat_image',
            field=models.ImageField(null=True, upload_to='images/cards/'),
        ),
        migrations.AddField(
            model_name='article',
            name='card_sm_image',
            field=models.ImageField(null=True, upload_to='images/cards/'),
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default='Test content.'),
        ),
        migrations.AddField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article',
            name='subtitle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='Test Article', max_length=80),
        ),
    ]
