# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20171108_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(default='Test summary.'),
        ),
    ]
