# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
