# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_article_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='card_avatar',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Member'),
        ),
    ]
