# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_article_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default='Article content.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(default='Article summary.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='Article Title', max_length=80),
        ),
    ]
