# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='asd', upload_to='images/gallery/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(default='Test Album', max_length=80),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default='Test Image', max_length=80),
        ),
    ]
