# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Test Post', max_length=80)),
                ('subtitle', models.CharField(max_length=200, null=True)),
                ('content', models.TextField(default='Test content.')),
                ('card_sm_image', models.ImageField(null=True, upload_to='images/cards/')),
                ('card_mat_image', models.ImageField(null=True, upload_to='images/cards/')),
                ('card_lg_image', models.ImageField(null=True, upload_to='images/cards/')),
                ('author', models.CharField(max_length=80, null=True)),
                ('card_avatar', models.ImageField(null=True, upload_to='images/avatars/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
