# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
