# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('blog', '0009_auto_20171128_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.Album'),
        ),
    ]
